version: "3.0"

services:
  app:
    build:
      context: .docker
    container_name: forum
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    entrypoint:
      - .docker/entrypoint.sh
    depends_on:
      - mysql
    networks:
      - forum

  mysql:
    image: mysql:8
    container_name: forum_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: forum
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_volume:/data/db
      
    networks:
      - forum

  
volumes:
  mysql_volume:
    driver: local

networks:
  forum:
    driver: bridge
